# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26134117dd645a9e4da94d8b74e4b1f557a205bda1fad2b50320ba6fe8afbfcf4befcabd284785941700cc90a774e8394f905dd3ab056c24a632d6cdf8315eb9

test:
  secret_key_base: 138e65d135f980d404adfa6ef50e7ba16b08ed3382f0ed94bd5387eab8c1e09c6efe9a3ea3d5af58c1573b1f970989847d4be2ca181f9061d76ed30f006b7e3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
